-- This script creates the tables required for the data lineage framework.
-- These tables are designed to store object and column level lineage information as a log.
-- This log-based approach is cost-efficient and robust for high query volumes.

CREATE SCHEMA IF NOT EXISTS LINEAGE;

-- Table to store object level lineage log
CREATE OR REPLACE TABLE LINEAGE.LINEAGE_OBJECT (
    SOURCE_OBJECT_NAME VARCHAR,
    SOURCE_OBJECT_DOMAIN VARCHAR,
    TARGET_OBJECT_NAME VARCHAR,
    TARGET_OBJECT_DOMAIN VARCHAR,
    QUERY_ID VARCHAR,
    QUERY_TYPE VARCHAR,
    QUERY_TEXT VARCHAR,
    QUERY_USER VARCHAR,
    QUERY_START_TIME TIMESTAMP_LTZ,
    INSERTION_TIME TIMESTAMP_LTZ
)
CLUSTER BY (QUERY_START_TIME, SOURCE_OBJECT_NAME, TARGET_OBJECT_NAME);

-- Table to store column level lineage log
CREATE OR REPLACE TABLE LINEAGE.LINEAGE_COLUMN (
    SOURCE_OBJECT_NAME VARCHAR,
    SOURCE_OBJECT_DOMAIN VARCHAR,
    SOURCE_COLUMN_NAME VARCHAR,
    TARGET_OBJECT_NAME VARCHAR,
    TARGET_OBJECT_DOMAIN VARCHAR,
    TARGET_COLUMN_NAME VARCHAR,
    QUERY_ID VARCHAR,
    QUERY_TYPE VARCHAR,
    QUERY_TEXT VARCHAR,
    QUERY_USER VARCHAR,
    QUERY_START_TIME TIMESTAMP_LTZ,
    INSERTION_TIME TIMESTAMP_LTZ
)
CLUSTER BY (QUERY_START_TIME, SOURCE_OBJECT_NAME, TARGET_OBJECT_NAME);
